### PR TITLE
[BUGFIX] Changed to stable dependencies

### PR DESCRIPTION
**Pull request by whythecode**

### CODE REVIEW

**Comment by remuslazar** [comment]
@yaramayer: cool, a "composer update" do not break anything then?

**Comment by whythecode** [comment]
nope, all worked! but it's probably better to wait until composer is changed in the base repo as well, otherwise it'll likely conflict

**Comment by whythecode** [comment]
p.s. this one had to be changed because it conflicted with the base repo when that one is set to stable

**Comment by remuslazar** [comment]
right, cool. Thanks!

**Pull request merged**
